// Auto-generated by pathManager.js
// Do not edit manually — edit config/paths.json instead.

const BASE_URL = "/acrx";
const API_BASE = "/acr/api";
const LOGIN_PATH = "/acroxa/login";
const LOGOUT_PATH = "/acrx/logout";
const DASHBOARD_PATH = "/acrx/dashboard";
const POSTS_PATH = "/acrx/posts";
const MEDIA_PATH = "/acrx/media";
const MEDIAUPLOAD_PATH = "/acrx/media/upload";
const CATEGORIES_PATH = "/acrx/categories";
const CATEGORYNEW_PATH = "/acrx/category/new";
const PROFILE_PATH = "/acrx/profile";
const SYSTEM_PATH = "/acrx/system";

export { BASE_URL, API_BASE, LOGIN_PATH, LOGOUT_PATH, DASHBOARD_PATH, POSTS_PATH, MEDIA_PATH, MEDIAUPLOAD_PATH, CATEGORIES_PATH, CATEGORYNEW_PATH, PROFILE_PATH, SYSTEM_PATH };