/* ../src/core/pathManager.js */
const fs = require("fs");
const path = require("path");

const configPath = path.join(__dirname, "../../config/paths.json");
function getPaths() {
  try {
    const data = fs.readFileSync(configPath, "utf-8");
    return JSON.parse(data);
  } catch (err) {
    console.error("❌ Error reading paths.json:", err);
    return { baseURL: "", routes: {} };
  }
}

function generateFrontendPaths() {
  const { baseURL, routes,apiBase } = getPaths();

  let jsContent = `// Auto-generated by pathManager.js\n`;
  jsContent += `// Do not edit manually — edit config/paths.json instead.\n\n`;

  jsContent += `const BASE_URL = "${baseURL}";\n`;
  jsContent += `const API_BASE = "${apiBase}";\n`;
  for (const [key, value] of Object.entries(routes)) {
    jsContent += `const ${key.toUpperCase()}_PATH = "${value}";\n`;
  }
  jsContent += `\nmodule.exports = { BASE_URL, API_BASE, ${Object.keys(routes)
    .map(k => k.toUpperCase() + "_PATH")
    .join(", ")} };`;

  const outputPath = path.resolve("config/generated-paths.js");
  fs.writeFileSync(outputPath, jsContent);
  console.log("✅ Generated frontend paths file.");
}

module.exports = { getPaths, generateFrontendPaths };
